"""Render the GitHub Pages dashboard from the same numbers score.py computes.

Two questions, answered at a glance:

  1. How much should I trust this thing right now?
  2. Where does it think tomorrow's price lands?

Generated by score.py on every daily run, so the page cannot drift from
CONTEXT.md — both read the same joined record in the same process. Static
HTML with no scripts and no external requests: the data changes once a day,
so there is nothing for a client-side fetch to do except add failure modes.

The honesty rules from DESIGN.md §7 apply here more than anywhere, because a
dashboard invites glancing rather than reading. A number on a page looks
authoritative whether or not it means anything, so the trust panel leads with
the verdict — usually "not yet" — and the supporting figures come after.
"""

from __future__ import annotations

import html
import math
from datetime import date as date_cls
from datetime import datetime, timezone

from thresholds import (
    DISPLAY_STEP,
    HEADLINE_THRESHOLD_C,
    PROB_COLUMNS,
    THRESHOLDS_C,
    price_ladder,
    snap,
    threshold_key,
)

# z for two-sided intervals under the Gaussian predictive distribution.
Z_80 = 1.2815515655446004
Z_50 = 0.6744897501960817

# How many days of price history the sparkline shows.
CHART_DAYS = 30


def _md(text: str) -> str:
    """Escape, then honour **bold**.

    score.py speaks markdown because CONTEXT.md is markdown. Dropping that
    straight into HTML rendered literal asterisks on the live page.
    """
    out = html.escape(text.lstrip("- ").strip())
    parts = out.split("**")
    return "".join(
        part if i % 2 == 0 else f"<strong>{part}</strong>"
        for i, part in enumerate(parts)
    )


def _f(value, places=4, dash="—"):
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return dash
    return f"{value:.{places}f}"


def trust_score(scored, by_mode, sizes, brier_headline, n_train):
    """How full the tank is: (fraction 0-1, label, one short sentence).

    A single gauge has to carry two different reasons for distrust, and the
    fraction deliberately conflates them while the label separates them:

      - **We don't know yet.** The needle sits low because evidence is thin.
      - **We know it's bad.** The needle also sits low, because a model
        measured and found no better than a coin flip has earned less trust
        than one that simply hasn't been measured.

    Both mean "don't lean on this", which is what the gauge is for. Anyone who
    wants to know which kind of low it is reads the label.

    The top of the range is reserved: nothing reaches Full without clearing the
    n_eff >= 50 gate AND beating the coin-flip baseline. Bootstrap forecasts are
    capped near Empty no matter how well they happen to score, because their
    scores say nothing about the model that replaces them.
    """
    if not scored:
        return 0.02, "Unproven", "Nothing has been scored yet."

    if not by_mode.get("model"):
        # Progress toward the fitted model, not toward trustworthiness.
        progress = min(n_train / 30.0, 1.0) if n_train else 0.0
        return (
            0.04 + 0.10 * progress,
            "Warming up",
            f"Still on the placeholder rule of thumb. The real model starts at "
            f"30 training days ({n_train}/30).",
        )

    n_eff = sizes.get("model", {}).get("binding", 0.0)
    if n_eff < 20:
        return (
            0.15 + 0.20 * (n_eff / 20.0),
            "Gathering evidence",
            f"The real model is running, but {n_eff:.0f} days of independent "
            "evidence is too few to judge it.",
        )
    if n_eff < 50 or brier_headline is None:
        return (
            0.35 + 0.15 * ((min(n_eff, 50.0) - 20.0) / 30.0),
            "Early signs",
            f"Enough evidence for a direction at {n_eff:.0f} independent days, "
            "not enough to trust a precise number.",
        )

    skill = 0.25 - brier_headline["brier"]
    if skill <= 0:
        return (
            0.08,
            "Measured, and not good",
            "Enough evidence now, and it says the forecasts are no better than "
            "a coin flip.",
        )

    # 0.10 of Brier skill is a strong daily forecaster; treat it as Full.
    fraction = 0.60 + 0.40 * min(skill / 0.10, 1.0)
    label = (
        "Extremely trustworthy" if fraction >= 0.85
        else "Trustworthy" if fraction >= 0.72
        else "Reasonably trustworthy"
    )
    return fraction, label, (
        f"Measured over {n_eff:.0f} independent days and beating a coin flip "
        f"by {skill:.3f}."
    )


def kind_for(fraction: float) -> str:
    """CSS class for the verdict line, matching where the needle sits."""
    if fraction >= 0.72:
        return "good"
    if fraction >= 0.35:
        return "directional"
    if fraction <= 0.10:
        return "poor"
    return "insufficient"


def _gauge(fraction: float) -> str:
    """A fuel gauge. Empty on the left, Full on the right, needle in between.

    Chosen over a number because the honest answer is a position on a spectrum,
    and a number invites a precision this does not have. Nobody misreads a fuel
    gauge as claiming to the decimal point.
    """
    fraction = max(0.0, min(1.0, fraction))
    cx, cy, r = 160.0, 152.0, 112.0
    theta = math.radians(180.0 - fraction * 180.0)
    nx, ny = cx + (r - 26) * math.cos(theta), cy - (r - 26) * math.sin(theta)

    ticks = []
    for i in range(5):
        a = math.radians(180.0 - (i / 4.0) * 180.0)
        x1, y1 = cx + (r - 9) * math.cos(a), cy - (r - 9) * math.sin(a)
        x2, y2 = cx + (r + 9) * math.cos(a), cy - (r + 9) * math.sin(a)
        ticks.append(f'<line class="tick" x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}"/>')

    return (
        f'<svg class="gauge" viewBox="0 0 320 184" role="img" '
        f'aria-label="Trustworthiness gauge, {fraction * 100:.0f} percent of full">'
        '<defs><linearGradient id="fuel" x1="0" y1="0" x2="1" y2="0">'
        '<stop offset="0%" stop-color="var(--bad)"/>'
        '<stop offset="50%" stop-color="var(--warn)"/>'
        '<stop offset="100%" stop-color="var(--ok)"/>'
        "</linearGradient></defs>"
        f'<path class="arc" d="M {cx - r:.0f} {cy:.0f} A {r:.0f} {r:.0f} 0 0 1 {cx + r:.0f} {cy:.0f}"/>'
        + "".join(ticks)
        + f'<line class="needle" x1="{cx:.0f}" y1="{cy:.0f}" x2="{nx:.1f}" y2="{ny:.1f}"/>'
        f'<circle class="pivot" cx="{cx:.0f}" cy="{cy:.0f}" r="7"/>'
        f'<text class="gmark" x="{cx - r:.0f}" y="{cy + 22:.0f}" text-anchor="middle">E</text>'
        f'<text class="gmark" x="{cx + r:.0f}" y="{cy + 22:.0f}" text-anchor="middle">F</text>'
        "</svg>"
    )


def _sparkline(prices, pending):
    """Price history with the pending forecast's 80% interval on the end."""
    days = sorted(prices)[-CHART_DAYS:]
    if len(days) < 2:
        return ""

    values = [prices[d] for d in days]
    lo_v, hi_v = min(values), max(values)

    band = None
    if pending:
        level = float(pending["level_at_forecast"]) * 100.0
        mu, sigma = float(pending["mu_cents"]), float(pending["sigma_cents"])
        band = (level + mu - Z_80 * sigma, level + mu + Z_80 * sigma, level + mu)
        lo_v, hi_v = min(lo_v, band[0]), max(hi_v, band[1])

    pad = max((hi_v - lo_v) * 0.12, 0.5)
    lo_v, hi_v = lo_v - pad, hi_v + pad
    w, h = 720.0, 200.0
    n = len(days) + (1 if band else 0)

    x = lambda i: 40 + (w - 60) * (i / max(n - 1, 1))
    y = lambda v: h - 24 - (h - 44) * ((v - lo_v) / max(hi_v - lo_v, 1e-9))

    pts = " ".join(f"{x(i):.1f},{y(v):.1f}" for i, v in enumerate(values))
    out = [
        f'<svg viewBox="0 0 {w:.0f} {h:.0f}" role="img" '
        f'aria-label="AAA national average, last {len(days)} days">',
        f'<polyline class="line" points="{pts}"/>',
    ]
    for i, v in enumerate(values):
        out.append(f'<circle class="dot" cx="{x(i):.1f}" cy="{y(v):.1f}" r="2.5"/>')

    if band:
        bx = x(n - 1)
        out.append(
            f'<line class="band" x1="{bx:.1f}" y1="{y(band[0]):.1f}" '
            f'x2="{bx:.1f}" y2="{y(band[1]):.1f}"/>'
        )
        out.append(f'<circle class="fc" cx="{bx:.1f}" cy="{y(band[2]):.1f}" r="4"/>')
        out.append(
            f'<text class="lbl" x="{bx - 6:.1f}" y="{y(band[1]) - 8:.1f}" '
            f'text-anchor="end">80% range</text>'
        )

    out.append(
        f'<text class="axis" x="40" y="{h - 6:.0f}">{days[0]}</text>'
        f'<text class="axis" x="{w - 20:.0f}" y="{h - 6:.0f}" '
        f'text-anchor="end">{days[-1]}</text>'
    )
    out.append("</svg>")
    return "".join(out)


CSS = """
:root{--bg:#fbfbfa;--fg:#1a1a19;--dim:#6b6b68;--line:#e0e0dc;--card:#fff;
--ok:#2f7d52;--warn:#a8620a;--bad:#a33a2e;--accent:#3d5a80}
@media (prefers-color-scheme:dark){:root{--bg:#161614;--fg:#eceae5;--dim:#9a9792;
--line:#33312d;--card:#1e1c1a;--ok:#6cc08a;--warn:#e0a057;--bad:#e0796a;--accent:#8fb3d9}}
*{box-sizing:border-box}
body{margin:0;padding:2rem 1.25rem 4rem;background:var(--bg);color:var(--fg);
font:16px/1.55 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif}
.wrap{max-width:820px;margin:0 auto}
h1{font-size:1.5rem;margin:0 0 .25rem}
.sub{color:var(--dim);font-size:.9rem;margin:0 0 2rem}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;
padding:1.25rem 1.4rem;margin:0 0 1.25rem}
.card h2{font-size:.78rem;text-transform:uppercase;letter-spacing:.07em;
color:var(--dim);margin:0 0 .9rem;font-weight:600}
.verdict{font-size:1.5rem;font-weight:650;margin:0 0 .5rem;line-height:1.25}
.verdict.none,.verdict.insufficient,.verdict.bootstrap{color:var(--warn)}
.verdict.directional{color:var(--accent)}
.verdict.good{color:var(--ok)}
.verdict.poor{color:var(--bad)}
.why{color:var(--dim);margin:0 0 1rem;font-size:.94rem}
.range{font-size:2rem;font-weight:650;letter-spacing:-.02em;margin:.1rem 0 .3rem}
.mid{font-size:1rem;color:var(--dim);margin:0 0 1rem}
table{width:100%;border-collapse:collapse;font-size:.9rem}
th,td{text-align:left;padding:.42rem .5rem;border-bottom:1px solid var(--line)}
th{color:var(--dim);font-weight:600;font-size:.8rem}
td.n,th.n{text-align:right;font-variant-numeric:tabular-nums}
.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:.9rem}
.fact .k{font-size:.75rem;color:var(--dim);text-transform:uppercase;letter-spacing:.05em}
.fact .v{font-size:1.15rem;font-weight:600;font-variant-numeric:tabular-nums}
svg{width:100%;height:auto;display:block;overflow:visible}
.line{fill:none;stroke:var(--accent);stroke-width:2}
.dot{fill:var(--accent)}
.band{stroke:var(--warn);stroke-width:8;stroke-linecap:round;opacity:.32}
.fc{fill:var(--warn)}
.lbl,.axis{font-size:11px;fill:var(--dim)}
.note{font-size:.86rem;color:var(--dim);border-left:3px solid var(--line);
padding-left:.9rem;margin:1rem 0 0}
code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.88em}
a{color:var(--accent)}
.scroll{overflow-x:auto}
.gaugewrap{max-width:340px;margin:0 auto 1rem}
.gauge{width:100%;height:auto;display:block}
.arc{fill:none;stroke:url(#fuel);stroke-width:14;stroke-linecap:round;opacity:.9}
.tick{stroke:var(--line);stroke-width:2}
.needle{stroke:var(--fg);stroke-width:4;stroke-linecap:round}
.pivot{fill:var(--fg)}
.gmark{font-size:15px;font-weight:700;fill:var(--dim)}
.gscale{display:flex;justify-content:space-between;font-size:.75rem;
color:var(--dim);margin-top:-.35rem}
.verdict{text-align:center}
.why{text-align:center}
details{margin-top:1.1rem}
summary{cursor:pointer;font-size:.85rem;color:var(--dim);
padding:.35rem 0;border-top:1px solid var(--line)}
details .why{text-align:left;font-size:.86rem;margin:.7rem 0 0}
"""


def render_site(scored, prices, forecasts, pending, by_mode, sizes,
                brier_headline, spread_line, coeff, n_train):
    """Build the full page. All inputs come from score.py's own computations."""
    now = datetime.now(timezone.utc).replace(microsecond=0)
    nxt = pending[-1] if pending else None
    E = html.escape

    p = []
    p.append(f"<style>{CSS}</style>")
    p.append('<div class="wrap">')
    p.append("<h1>AAA national average — daily forecast</h1>")
    p.append(
        f'<p class="sub">Updated {now.isoformat()} · '
        '<a href="https://github.com/parallax-parking/daily-gas-prices">source</a> · '
        '<a href="https://github.com/parallax-parking/daily-gas-prices/blob/main/CONTEXT.md">full report</a></p>'
    )

    # --- 1. trust -----------------------------------------------------------
    fraction, verdict, why = trust_score(
        scored, by_mode, sizes, brier_headline, n_train
    )
    p.append('<div class="card">')
    p.append("<h2>How much to trust this</h2>")
    p.append('<div class="gaugewrap">')
    p.append(_gauge(fraction))
    p.append('<div class="gscale"><span>Not trustworthy</span>'
             "<span>Extremely trustworthy</span></div>")
    p.append("</div>")
    p.append(f'<p class="verdict {E(kind_for(fraction))}">{E(verdict)}</p>')
    p.append(f'<p class="why">{E(why)}</p>')

    model_n = len(by_mode.get("model", []))
    prior_n = len(by_mode.get("prior", []))
    n_eff = sizes.get("model", {}).get("binding") or sizes.get("prior", {}).get("binding")
    p.append('<div class="facts">')
    p.append(f'<div class="fact"><div class="k">Days scored</div>'
             f'<div class="v">{len(scored)}</div></div>')
    p.append(f'<div class="fact"><div class="k">Independent days</div>'
             f'<div class="v">{_f(n_eff, 1)}</div></div>')
    p.append(f'<div class="fact"><div class="k">Real / placeholder</div>'
             f'<div class="v">{model_n} / {prior_n}</div></div>')
    p.append(f'<div class="fact"><div class="k">Until real model</div>'
             f'<div class="v">{n_train} / 30</div></div>')
    p.append("</div>")

    # Everything below is true and occasionally important, and none of it
    # belongs in the first five seconds. <details> keeps it a click away
    # without a line of JavaScript.
    p.append("<details><summary>What these numbers mean</summary>")
    p.append(
        '<p class="why"><strong>Independent days</strong> is not the number of '
        "days. Two forecasts made a day apart are nearly the same bet, so this "
        "counts how much genuinely separate evidence there is — always less, "
        "often by half.</p>"
    )
    p.append(f'<p class="why">{_md(spread_line)}</p>')
    p.append(
        '<p class="why">The gauge stays near Empty until the real model has '
        "been measured over enough independent days to beat a coin flip. A "
        "model that has been measured and found wanting sits low too — the "
        "label says which.</p>"
    )
    p.append("</details>")
    p.append("</div>")

    # --- 2. tomorrow --------------------------------------------------------
    p.append('<div class="card">')
    if nxt:
        level = float(nxt["level_at_forecast"])
        mu, sigma = float(nxt["mu_cents"]), float(nxt["sigma_cents"])
        centre = level + mu / 100.0
        lo80, hi80 = centre - Z_80 * sigma / 100.0, centre + Z_80 * sigma / 100.0
        lo50, hi50 = centre - Z_50 * sigma / 100.0, centre + Z_50 * sigma / 100.0

        # Interval ends snap OUTWARD onto the display grid. Rounding inward
        # would advertise a range narrower than the one actually claimed —
        # overconfidence by presentation, which is the failure this project
        # works hardest to avoid. Hence "at least 80%".
        lo80_s, hi80_s = snap(lo80, mode="down"), snap(hi80, mode="up")
        lo50_s, hi50_s = snap(lo50, mode="down"), snap(hi50, mode="up")

        p.append(f'<h2>Where {E(nxt["target_date"])} lands</h2>')
        p.append(f'<p class="range">${lo80_s:.3f} – ${hi80_s:.3f}</p>')
        p.append(
            f'<p class="mid">At least 80% confidence. Middle estimate '
            f'<strong>${snap(centre):.3f}</strong> ({mu:+.2f}¢ from '
            f'${level:.4f}). Even odds it lands between ${lo50_s:.3f} and '
            f'${hi50_s:.3f}.</p>'
        )

        today_rung = snap(level)
        p.append('<div class="scroll"><table><thead><tr>'
                 '<th>Chance the price is above</th><th class="n">Probability</th>'
                 '</tr></thead><tbody>')
        for price, prob in price_ladder(level, mu, sigma):
            mark = " <strong>(today)</strong>" if abs(price - today_rung) < 1e-9 else ""
            p.append(f'<tr><td>${price:.3f}{mark}</td>'
                     f'<td class="n">{prob * 100:.1f}%</td></tr>')
        p.append("</tbody></table></div>")
        p.append(
            f'<p class="note">Prices are shown in ${DISPLAY_STEP:.3f} steps for '
            "readability. The probabilities are computed from the forecast's "
            "own centre and spread, not rounded off a stored table, so every "
            "rung is exact for the price beside it.</p>"
        )
        if nxt.get("mode") == "prior":
            p.append(
                '<p class="note">This came from the bootstrap prior, not the '
                "fitted model. It carries a third of the recent average change "
                "forward and assumes a fixed 1¢ spread, so it lags any turn "
                "and its range is a guess rather than a measurement.</p>"
            )
    else:
        p.append("<h2>Next forecast</h2>")
        p.append('<p class="why">No forecast is currently awaiting an outcome. '
                 "The next one is written by today's scheduled run.</p>")
    p.append("</div>")

    # --- 3. history ---------------------------------------------------------
    chart = _sparkline(prices, nxt)
    if chart:
        p.append('<div class="card"><h2>Recent prices</h2>')
        p.append(chart)
        p.append('<p class="note">Blue is what AAA published. The orange bar is '
                 "the 80% range for the next day.</p></div>")

    # --- 4. what it is keying on -------------------------------------------
    p.append('<div class="card"><h2>What the model is keying on</h2>')
    if coeff:
        p.append('<div class="scroll"><table><thead><tr><th>Feature</th>'
                 '<th class="n">Weight</th></tr></thead><tbody>')
        for name, weight in coeff:
            p.append(f'<tr><td><code>{E(name)}</code></td>'
                     f'<td class="n">{weight:+.3f}</td></tr>')
        p.append("</tbody></table></div>")
    else:
        p.append(f'<p class="why">Not fitted yet — needs 30 complete training '
                 f"rows and has {n_train}.</p>")
    p.append("</div>")

    p.append(
        '<p class="note">The forecast is not the product; the calibration '
        "record is. This page is generated on every daily run from the same "
        "data as the full report, and is never hand-edited.</p>"
    )
    p.append("</div>")
    return "\n".join(p) + "\n"
