"""Render the GitHub Pages dashboard from the same numbers score.py computes.

Two questions, answered at a glance:

  1. How much should I trust this thing right now?
  2. Where does it think tomorrow's price lands?

Generated by score.py on every daily run, so the page cannot drift from
CONTEXT.md — both read the same joined record in the same process. Static
HTML with no scripts and no external requests: the data changes once a day,
so there is nothing for a client-side fetch to do except add failure modes.

The honesty rules from DESIGN.md §7 apply here more than anywhere, because a
dashboard invites glancing rather than reading. A number on a page looks
authoritative whether or not it means anything, so the trust panel leads with
the verdict — usually "not yet" — and the supporting figures come after.
"""

from __future__ import annotations

import html
import math
from datetime import date as date_cls
from datetime import datetime, timezone

from thresholds import (
    DISPLAY_STEP,
    HEADLINE_THRESHOLD_C,
    PROB_COLUMNS,
    THRESHOLDS_C,
    price_ladder,
    snap,
    threshold_key,
)

# z for two-sided intervals under the Gaussian predictive distribution.
Z_80 = 1.2815515655446004
Z_50 = 0.6744897501960817

# How many days of price history the sparkline shows.
CHART_DAYS = 30


def _f(value, places=4, dash="—"):
    if value is None or (isinstance(value, float) and math.isnan(value)):
        return dash
    return f"{value:.{places}f}"


def trust_verdict(scored, by_mode, sizes, brier_headline):
    """The headline answer to "should I believe this yet?".

    Deliberately pessimistic. The system spends its first months unable to
    support any claim, and the page should say so in the largest text on it
    rather than burying it under a plausible-looking Brier score.
    """
    if not scored:
        return ("none", "No evidence yet",
                "Nothing has been scored. A forecast can only be scored once "
                "its target date has been observed.")

    model_rows = by_mode.get("model", [])
    if not model_rows:
        return ("bootstrap", "Not the real model yet",
                "Every forecast so far comes from the bootstrap prior — a rule "
                "of thumb that carries a third of the recent average change "
                "forward. It cannot anticipate a turn, and its scores say "
                "nothing about the fitted model that replaces it.")

    n_eff = sizes.get("model", {}).get("binding", 0.0)
    if n_eff < 20:
        return ("insufficient", "Not measurable yet",
                f"The fitted model has {n_eff:.0f} effective observations. "
                "Below 20, nothing here supports a claim about calibration.")
    if n_eff < 50:
        return ("directional", "Directional read only",
                f"At {n_eff:.0f} effective observations, treat gaps under 10 "
                "percentage points as noise.")

    if brier_headline is None:
        return ("directional", "Directional read only",
                "Not enough scored forecasts at the headline threshold.")

    skill = 0.25 - brier_headline["brier"]
    if skill <= 0:
        return ("poor", "No better than a coin flip",
                f"Headline Brier {brier_headline['brier']:.3f} against 0.250 "
                "for a forecaster that always says 50%.")
    return ("good", "Calibrated read available",
            f"Headline Brier {brier_headline['brier']:.3f}, "
            f"{skill:+.3f} better than always saying 50%.")


def _sparkline(prices, pending):
    """Price history with the pending forecast's 80% interval on the end."""
    days = sorted(prices)[-CHART_DAYS:]
    if len(days) < 2:
        return ""

    values = [prices[d] for d in days]
    lo_v, hi_v = min(values), max(values)

    band = None
    if pending:
        level = float(pending["level_at_forecast"]) * 100.0
        mu, sigma = float(pending["mu_cents"]), float(pending["sigma_cents"])
        band = (level + mu - Z_80 * sigma, level + mu + Z_80 * sigma, level + mu)
        lo_v, hi_v = min(lo_v, band[0]), max(hi_v, band[1])

    pad = max((hi_v - lo_v) * 0.12, 0.5)
    lo_v, hi_v = lo_v - pad, hi_v + pad
    w, h = 720.0, 200.0
    n = len(days) + (1 if band else 0)

    x = lambda i: 40 + (w - 60) * (i / max(n - 1, 1))
    y = lambda v: h - 24 - (h - 44) * ((v - lo_v) / max(hi_v - lo_v, 1e-9))

    pts = " ".join(f"{x(i):.1f},{y(v):.1f}" for i, v in enumerate(values))
    out = [
        f'<svg viewBox="0 0 {w:.0f} {h:.0f}" role="img" '
        f'aria-label="AAA national average, last {len(days)} days">',
        f'<polyline class="line" points="{pts}"/>',
    ]
    for i, v in enumerate(values):
        out.append(f'<circle class="dot" cx="{x(i):.1f}" cy="{y(v):.1f}" r="2.5"/>')

    if band:
        bx = x(n - 1)
        out.append(
            f'<line class="band" x1="{bx:.1f}" y1="{y(band[0]):.1f}" '
            f'x2="{bx:.1f}" y2="{y(band[1]):.1f}"/>'
        )
        out.append(f'<circle class="fc" cx="{bx:.1f}" cy="{y(band[2]):.1f}" r="4"/>')
        out.append(
            f'<text class="lbl" x="{bx - 6:.1f}" y="{y(band[1]) - 8:.1f}" '
            f'text-anchor="end">80% range</text>'
        )

    out.append(
        f'<text class="axis" x="40" y="{h - 6:.0f}">{days[0]}</text>'
        f'<text class="axis" x="{w - 20:.0f}" y="{h - 6:.0f}" '
        f'text-anchor="end">{days[-1]}</text>'
    )
    out.append("</svg>")
    return "".join(out)


CSS = """
:root{--bg:#fbfbfa;--fg:#1a1a19;--dim:#6b6b68;--line:#e0e0dc;--card:#fff;
--ok:#2f7d52;--warn:#a8620a;--bad:#a33a2e;--accent:#3d5a80}
@media (prefers-color-scheme:dark){:root{--bg:#161614;--fg:#eceae5;--dim:#9a9792;
--line:#33312d;--card:#1e1c1a;--ok:#6cc08a;--warn:#e0a057;--bad:#e0796a;--accent:#8fb3d9}}
*{box-sizing:border-box}
body{margin:0;padding:2rem 1.25rem 4rem;background:var(--bg);color:var(--fg);
font:16px/1.55 ui-sans-serif,-apple-system,"Segoe UI",Roboto,sans-serif}
.wrap{max-width:820px;margin:0 auto}
h1{font-size:1.5rem;margin:0 0 .25rem}
.sub{color:var(--dim);font-size:.9rem;margin:0 0 2rem}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;
padding:1.25rem 1.4rem;margin:0 0 1.25rem}
.card h2{font-size:.78rem;text-transform:uppercase;letter-spacing:.07em;
color:var(--dim);margin:0 0 .9rem;font-weight:600}
.verdict{font-size:1.5rem;font-weight:650;margin:0 0 .5rem;line-height:1.25}
.verdict.none,.verdict.insufficient,.verdict.bootstrap{color:var(--warn)}
.verdict.directional{color:var(--accent)}
.verdict.good{color:var(--ok)}
.verdict.poor{color:var(--bad)}
.why{color:var(--dim);margin:0 0 1rem;font-size:.94rem}
.range{font-size:2rem;font-weight:650;letter-spacing:-.02em;margin:.1rem 0 .3rem}
.mid{font-size:1rem;color:var(--dim);margin:0 0 1rem}
table{width:100%;border-collapse:collapse;font-size:.9rem}
th,td{text-align:left;padding:.42rem .5rem;border-bottom:1px solid var(--line)}
th{color:var(--dim);font-weight:600;font-size:.8rem}
td.n,th.n{text-align:right;font-variant-numeric:tabular-nums}
.facts{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:.9rem}
.fact .k{font-size:.75rem;color:var(--dim);text-transform:uppercase;letter-spacing:.05em}
.fact .v{font-size:1.15rem;font-weight:600;font-variant-numeric:tabular-nums}
svg{width:100%;height:auto;display:block;overflow:visible}
.line{fill:none;stroke:var(--accent);stroke-width:2}
.dot{fill:var(--accent)}
.band{stroke:var(--warn);stroke-width:8;stroke-linecap:round;opacity:.32}
.fc{fill:var(--warn)}
.lbl,.axis{font-size:11px;fill:var(--dim)}
.note{font-size:.86rem;color:var(--dim);border-left:3px solid var(--line);
padding-left:.9rem;margin:1rem 0 0}
code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.88em}
a{color:var(--accent)}
.scroll{overflow-x:auto}
"""


def render_site(scored, prices, forecasts, pending, by_mode, sizes,
                brier_headline, spread_line, coeff, n_train):
    """Build the full page. All inputs come from score.py's own computations."""
    now = datetime.now(timezone.utc).replace(microsecond=0)
    kind, verdict, why = trust_verdict(scored, by_mode, sizes, brier_headline)
    nxt = pending[-1] if pending else None
    E = html.escape

    p = []
    p.append(f"<style>{CSS}</style>")
    p.append('<div class="wrap">')
    p.append("<h1>AAA national average — daily forecast</h1>")
    p.append(
        f'<p class="sub">Updated {now.isoformat()} · '
        '<a href="https://github.com/parallax-parking/daily-gas-prices">source</a> · '
        '<a href="https://github.com/parallax-parking/daily-gas-prices/blob/main/CONTEXT.md">full report</a></p>'
    )

    # --- 1. trust -----------------------------------------------------------
    p.append('<div class="card">')
    p.append("<h2>How much to trust this</h2>")
    p.append(f'<p class="verdict {kind}">{E(verdict)}</p>')
    p.append(f'<p class="why">{E(why)}</p>')
    p.append('<div class="facts">')
    model_n = len(by_mode.get("model", []))
    prior_n = len(by_mode.get("prior", []))
    n_eff = sizes.get("model", {}).get("binding") or sizes.get("prior", {}).get("binding")
    p.append(f'<div class="fact"><div class="k">Scored</div>'
             f'<div class="v">{len(scored)}</div></div>')
    p.append(f'<div class="fact"><div class="k">Effective n</div>'
             f'<div class="v">{_f(n_eff, 1)}</div></div>')
    p.append(f'<div class="fact"><div class="k">Fitted / bootstrap</div>'
             f'<div class="v">{model_n} / {prior_n}</div></div>')
    p.append(f'<div class="fact"><div class="k">Training rows</div>'
             f'<div class="v">{n_train} / 30</div></div>')
    p.append("</div>")
    p.append(f'<p class="note">{E(spread_line.lstrip("- "))}</p>')
    if not by_mode.get("model"):
        p.append(
            '<p class="note"><strong>Effective n</strong> is not the number of '
            "days. Consecutive forecasts are nearly the same bet, so it counts "
            "independent evidence, which is always less.</p>"
        )
    p.append("</div>")

    # --- 2. tomorrow --------------------------------------------------------
    p.append('<div class="card">')
    if nxt:
        level = float(nxt["level_at_forecast"])
        mu, sigma = float(nxt["mu_cents"]), float(nxt["sigma_cents"])
        centre = level + mu / 100.0
        lo80, hi80 = centre - Z_80 * sigma / 100.0, centre + Z_80 * sigma / 100.0
        lo50, hi50 = centre - Z_50 * sigma / 100.0, centre + Z_50 * sigma / 100.0

        # Interval ends snap OUTWARD onto the display grid. Rounding inward
        # would advertise a range narrower than the one actually claimed —
        # overconfidence by presentation, which is the failure this project
        # works hardest to avoid. Hence "at least 80%".
        lo80_s, hi80_s = snap(lo80, mode="down"), snap(hi80, mode="up")
        lo50_s, hi50_s = snap(lo50, mode="down"), snap(hi50, mode="up")

        p.append(f'<h2>Where {E(nxt["target_date"])} lands</h2>')
        p.append(f'<p class="range">${lo80_s:.3f} – ${hi80_s:.3f}</p>')
        p.append(
            f'<p class="mid">At least 80% confidence. Middle estimate '
            f'<strong>${snap(centre):.3f}</strong> ({mu:+.2f}¢ from '
            f'${level:.4f}). Even odds it lands between ${lo50_s:.3f} and '
            f'${hi50_s:.3f}.</p>'
        )

        today_rung = snap(level)
        p.append('<div class="scroll"><table><thead><tr>'
                 '<th>Chance the price is above</th><th class="n">Probability</th>'
                 '</tr></thead><tbody>')
        for price, prob in price_ladder(level, mu, sigma):
            mark = " <strong>(today)</strong>" if abs(price - today_rung) < 1e-9 else ""
            p.append(f'<tr><td>${price:.3f}{mark}</td>'
                     f'<td class="n">{prob * 100:.1f}%</td></tr>')
        p.append("</tbody></table></div>")
        p.append(
            f'<p class="note">Prices are shown in ${DISPLAY_STEP:.3f} steps for '
            "readability. The probabilities are computed from the forecast's "
            "own centre and spread, not rounded off a stored table, so every "
            "rung is exact for the price beside it.</p>"
        )
        if nxt.get("mode") == "prior":
            p.append(
                '<p class="note">This came from the bootstrap prior, not the '
                "fitted model. It carries a third of the recent average change "
                "forward and assumes a fixed 1¢ spread, so it lags any turn "
                "and its range is a guess rather than a measurement.</p>"
            )
    else:
        p.append("<h2>Next forecast</h2>")
        p.append('<p class="why">No forecast is currently awaiting an outcome. '
                 "The next one is written by today's scheduled run.</p>")
    p.append("</div>")

    # --- 3. history ---------------------------------------------------------
    chart = _sparkline(prices, nxt)
    if chart:
        p.append('<div class="card"><h2>Recent prices</h2>')
        p.append(chart)
        p.append('<p class="note">Blue is what AAA published. The orange bar is '
                 "the 80% range for the next day.</p></div>")

    # --- 4. what it is keying on -------------------------------------------
    p.append('<div class="card"><h2>What the model is keying on</h2>')
    if coeff:
        p.append('<div class="scroll"><table><thead><tr><th>Feature</th>'
                 '<th class="n">Weight</th></tr></thead><tbody>')
        for name, weight in coeff:
            p.append(f'<tr><td><code>{E(name)}</code></td>'
                     f'<td class="n">{weight:+.3f}</td></tr>')
        p.append("</tbody></table></div>")
    else:
        p.append(f'<p class="why">Not fitted yet — needs 30 complete training '
                 f"rows and has {n_train}.</p>")
    p.append("</div>")

    p.append(
        '<p class="note">The forecast is not the product; the calibration '
        "record is. This page is generated on every daily run from the same "
        "data as the full report, and is never hand-edited.</p>"
    )
    p.append("</div>")
    return "\n".join(p) + "\n"
